# -*- coding: utf-8 -*-

SET_HEADING_COMMAND = 'set_heading'
SET_SUBHEADING_COMMAND = 'set_subheading'
SET_BLACKOUT_COMMAND = 'set_blackout_intensity'
SET_BLUR_COMMAND = 'set_blur_radius'
SEND_NEWSLETTER_COMMAND = 'send_newsletter'
SET_MAILING_LIST_COMMAND = 'set_mailing_list'

SET_PHOTO_PARAMETER_COMMANDS = [SET_HEADING_COMMAND, SET_SUBHEADING_COMMAND, SET_BLACKOUT_COMMAND, SET_BLUR_COMMAND]
